import express from 'express';
import compression from 'compression';
import helmet from 'helmet';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const app = express();
const PORT = process.env.PORT || 3000;
app.use(helmet());
app.use(compression());
app.use(express.static(__dirname, { index: 'index.html' }));
app.get('/health', (_req, res) => res.status(200).json({ ok: true }));
app.listen(PORT, () => { console.log(`My Set server running on port ${PORT}`); });